export default {
  bandDesc: {
    expand: '1949–54. Deeply moved by Matisse\'s color and the scale of Renaissance frescoes during his European tour, Rothko returned to perfect his classic color-field style. The birth of daughter Kate (1950), participation in MoMA\'s "15 Americans" exhibition (1952), and a solo show at the Art Institute of Chicago — artistic recognition and personal happiness reached their peak simultaneously. Canvases were filled with luminous color fields of orange, red, and yellow. These are the works from the period when Rothko himself said he was expressing "basic human emotions — tragedy, ecstasy, doom."',
    radiate: '1945–48. After divorcing his first wife Edith (1944), Rothko married illustrator Mell Beistle (1945) and made a fresh start. He held his first solo exhibition at Peggy Guggenheim\'s Art of This Century gallery (1945) and co-founded the Subjects of the Artist school with fellow painters (1948). The remnants of figuration gradually dissolved as the Multiform style was born — forms floated freely and colors began to vibrate autonomously. A period of radiance, where the energy of new love and artistic breakthrough expanded beyond the canvas.',
    equil: '1938–44. A transitional period as Rothko, who had been exploring urban solitude in his New York subway series, became immersed in Nietzsche and Greek tragedy, shifting toward mythological surrealism. He had not yet reached pure abstraction but was leaving figuration behind — the tension between two worlds coexisted tautly on the canvas. Personally, he was also trying to find balance between marital conflict and his identity as an immigrant. Neither expanding nor contracting — works in a meditative equilibrium, the stillness just before transformation.',
    contract: '1958–67. Commissioned to create the Seagram Murals for New York\'s elite Four Seasons restaurant, Rothko declared he would "ruin the appetite of every son of a bitch who ever eats in that room," ultimately breaking the contract and reclaiming his paintings (1959). As Pop Art rose, Abstract Expressionism was criticized as anachronistic, and Rothko grew increasingly isolated. He undertook monumental projects including the Harvard Murals (1962) and the Rothko Chapel commission (1964), but excessive drinking and depression deepened as his health deteriorated. Colors condensed into deep maroon, dark red, and black — energy could no longer radiate outward but sank deep into the interior of the canvas.',
    void: '1968–70. Diagnosed with an aortic aneurysm, Rothko refused to stop working despite doctors\' warnings. Separated from his wife Mell, he lived alone in his studio, devoted to his final series "Black on Gray." Composed of only two horizontal planes of black and gray, these works show the complete extinction of his former chromatic energy. "Silence and solitude are my only companions," Rothko had said. On February 25, 1970, he ended his own life at his East 69th Street studio in New York. His final works are both the dissolution of form and the reduction of color — the very process of existence resolving into stillness.',
  },
};
